package v1alpha1

import "encoding/json"

// CustomizedValue provides a wrapper around map[string]any to allow for flexible,
// protocol-specific configuration data while enabling DeepCopy functionality
// through manual implementation using JSON marshaling.
// +kubebuilder:validation:Type=object
// +kubebuilder:pruning:PreserveUnknownFields
type CustomizedValue struct {
	// Data holds the arbitrary key-value configuration.
	// Keys are strings, values can be strings, numbers, booleans, lists, or nested objects,
	// provided they are JSON serializable.
	Data map[string]any `json:"-"` // Use json:",inline" if Data should be flattened, but '-' avoids direct marshaling conflict
}

// MarshalJSON implements the Marshaler interface.
// It marshals the internal Data map directly.
func (in *CustomizedValue) MarshalJSON() ([]byte, error) {
	if in == nil {
		// Handle nil receiver case, perhaps return null or an empty object bytes
		return []byte("null"), nil
	}
	return json.Marshal(in.Data)
}

// UnmarshalJSON implements the Unmarshaler interface.
// It unmarshals the JSON data into the internal Data map.
func (in *CustomizedValue) UnmarshalJSON(data []byte) error {
	var out map[string]any
	err := json.Unmarshal(data, &out)
	if err != nil {
		return err
	}
	in.Data = out
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
// Manually implemented using JSON marshal/unmarshal for deep copying map[string]any.
func (in *CustomizedValue) DeepCopyInto(out *CustomizedValue) {
	bytes, err := json.Marshal(in.Data)
	if err != nil {
		panic(err)
	}
	var clone map[string]any
	err = json.Unmarshal(bytes, &clone)
	if err != nil {
		panic(err)
	}
	out.Data = clone
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizedValue.
// Manually implemented using DeepCopyInto.
func (in *CustomizedValue) DeepCopy() *CustomizedValue {
	if in == nil {
		return nil
	}
	out := new(CustomizedValue)
	in.DeepCopyInto(out)
	return out
}

// Note: CustomizedValue doesn't implement DeepCopyObject as it's not a root Kubernetes object.
