apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  # For production, use at least 2 replicas for high availability
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cpeer-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller-manager
      labels:
        app.kubernetes.io/name: cpeer-controller-manager
    spec:
      # Ensure deployment on compatible nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: controller-manager
        # Placeholder image, to be replaced by Kustomize
        image: controller-manager-placeholder
        command:
        - /cpeer-controller-manager # Assuming the binary name in the image is cpeer-controller-manager
        args:
        # Pass namespace and address as arguments
        - --log.caller-skip 0      
        ports:
        - name: health
          containerPort: 9001
          protocol: TCP
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        # Health and readiness probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        # Resource requests and limits (adjust after performance testing)
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10