---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # This name must match the name of the ClusterRole in generated.manager-role.yaml
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  # The namespace will be injected by Kustomize from the overlay.
  namespace: system